In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from keras.models import Sequential
from sklearn.neural_network import MLPClassifier
from keras.layers import Dense, Dropout, Activation, Flatten
from sklearn.metrics import plot_confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegressionCV
from sklearn.ensemble import RandomForestClassifier
from keras.utils import np_utils
import seaborn as sn
import matplotlib.pyplot as plt
import matplotlib
import pandas as pd
import numpy as np

df = pd.DataFrame()

In [2]:
df=pd.read_csv('./Balanced_dataset.csv')

In [5]:
df

,age,sex,city,province,country,lives_in_Wuhan,travel_history_location,chronic_disease_binary,chronic_disease,chronic_disease_Hypertension,...,shortness of breath,somnolence,sore throat,sputum,septic shock,Heart attack,cold,cardiac disease,hypoxia,outcome
0,65.0,0,city,Washington,United States,NaN,NaN,0,NaN,0,...,0,0,0,0,0,0,0,0,0,recovered
1,54.0,0,Taguig,Metro Manila,Philippines,NaN,NaN,0,NaN,0,...,0,0,0,0,0,0,0,0,0,recovered
2,40.0,0,Pasay,Metro Manila,Philippines,NaN,NaN,0,NaN,0,...,0,0,0,0,0,0,0,0,0,recovered
3,28.0,0,Muntinlupa,Metro Manila,Philippines,NaN,NaN,0,NaN,0,...,0,0,0,0,0,0,0,0,0,recovered
4,30.0,0,Cainta,Rizal,Philippines,NaN,NaN,0,NaN,0,...,0,0,0,0,0,0,0,0,0,recovered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12015,43.0,1,Sant Kabir Nagar,Uttar Pradesh,India,NaN,NaN,0,NaN,0,...,0,0,0,0,0,0,0,0,0,died
12016,43.0,1,Mumbai,Maharashtra,India,NaN,NaN,0,NaN,0,...,0,0,0,0,0,0,0,0,0,died
12017,43.0,1,Siddharthnagar,Uttar Pradesh,India,NaN,NaN,0,NaN,0,...,0,0,0,0,0,0,0,0,0,died
12018,94.0,1,Miagao,Iloilo Province,Philippines,NaN,NaN,0,NaN,0,...,0,0,0,0,0,0,0,0,0,died
12019,43.0,1,Ahmedabad,Gujarat,India,NaN,NaN,0,NaN,0,...,0,0,0,1,0,0,0,0,0,died